In [20]:
import sklearn.linear_model
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
import pandas as pd
import numpy as np

#/generate
#

In [37]:
train_data = pd.read_csv('data/mercedes/train.csv')
test_data = pd.read_csv('data/mercedes/test.csv')
enc = LabelEncoder()
#transforming categorical data into numbers. If this isn't working, I should try one-hot encoding instead of label encoding.
for col_title in train_data:# not sure how to generalize this for no titles 
    if train_data[col_title].dtype==object:
        train_data[col_title] = enc.fit_transform(train_data[col_title])
train_data.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,32,23,17,0,3,24,9,14,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,32,21,19,4,3,28,11,14,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,20,24,34,2,3,27,9,23,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,20,21,34,5,3,27,11,4,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,20,23,34,5,3,12,3,13,...,0,0,0,0,0,0,0,0,0,0

In [38]:
model = sklearn.linear_model.LinearRegression()
model.fit(X=train_data.drop(columns='y', axis=1), y=train_data['y'])
model.score(X=train_data.drop(columns='y', axis=1), y=train_data['y'])

0.5935201743332184

In [42]:
model = sklearn.linear_model.SGDRegressor(loss="squared_error", max_iter = 100_000)
model.fit(X=train_data.drop(columns='y', axis=1), y=train_data['y'])
model.score(X=train_data.drop(columns='y', axis=1), y=train_data['y'])

-4.199308285163361e+28